---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: hello
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - port: 5000
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: lb
  namespace: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 5000
    targetPort: 8080

